### ISSUE TITLE
Why keep multiple versions in the repo?

### ISSUE THREAD

**Issue by aspiers** [MarcGamesons/twitch-userscript-use-chitchat#8]
Is there any benefit to keeping old versions in the repo?  The whole point of git is to keep old history, so it seems to me that they could be deleted from the repo to simplify it.  Similarly I'm confused by the presence of identical copies of the file in `src/latest/` and `src/update/`.

**Comment by MarcGamesons** [comment]
You are right. I should reorganize this repository. The `src/latest/` and `src/update/` folder are only still both existant because some of my older script versions use update for updating and some use latest for updating. I should change the path in the script instead and remove both of them.

If the script breaks and users are still interested in it, they might come here and download a newer version.

I was and am still learning how to use GitHub properly.
